apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: worming/http-helloworld
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
        startupProbe:
          httpGet:
            path: "/readyz"
            port: 8000
          periodSeconds: 2
          initialDelaySeconds: 8
        imagePullPolicy: Always