apiVersion: v1
kind: Pod
metadata:
  name: hello
  labels:
    name: hello # le label est utilisé plus tard, retenez "name: hello"
spec:
  containers:
  - name: hello
    image: worming/http-helloworld
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8000
