apiVersion: v1
kind: Namespace
metadata:
  name: hpa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: horizontal-scaling
  namespace: hpa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: horizontal-scaling
  template:
    metadata:
      labels:
        app: horizontal-scaling
    spec:
      containers:
      - name: horizontal-scaling 
        image: worming/http-fibonacci
        resources:
          limits:
            memory: "128Mi"
            cpu: "10m"
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: horizontal-scaling
  namespace: hpa
spec:
  selector:
    app: horizontal-scaling
  ports:
  - port: 8000
    targetPort: 8000
  type: LoadBalancer